//Get all users
GET http://localhost:9000/users

###

//Get single user by Id
GET http://localhost:9000/users/61370cacb2fe622c0de13e46

###

//Delete user 
DELETE http://localhost:9000/users/613c9f9c665c4dc7e7fe4407

###

//Create new user
POST http://localhost:9000/users/register
Content-Type: application/json

{
    "username": "admin4",
    "password": "admin4"
}

###

//Login API
POST http://localhost:9000/users/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

//Update - get token in login api
POST http://localhost:9000/users/change-password/
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzcwY2FjYjJmZTYyMmMwZGUxM2U0NiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzE1MTg3ODd9.XFDyoGYsUlIVcCSLwzLcEIowQU9Gff9bu2axX494-MI"

{
    "newpassword": "admin",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzcwY2FjYjJmZTYyMmMwZGUxM2U0NiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzE1MTg3ODd9.XFDyoGYsUlIVcCSLwzLcEIowQU9Gff9bu2axX494-MI"
}

###

//Update user using id
PATCH http://localhost:9000/users/change-password/61370d26b2fe622c0de13e4c
// 61370cacb2fe622c0de13e46
Content-Type: application/json

{
    "newpassword": "admin1"
}

###
